# Generated by Django 5.1.1 on 2024-11-02 20:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('c', 'C'), ('javascript', 'JavaScript')], max_length=20)),
                ('template_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['language', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the code snippet', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what the code does')),
                ('code', models.TextField(help_text='The actual code content', validators=[django.core.validators.MaxLengthValidator(50000)])),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('c', 'C'), ('javascript', 'JavaScript')], help_text='Programming language of the code', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this snippet is publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this snippet', on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Code that was executed')),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('c', 'C'), ('javascript', 'JavaScript')], help_text='Programming language used', max_length=20)),
                ('output', models.TextField(blank=True, help_text='Output of code execution')),
                ('error', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], help_text='Status of code execution', max_length=10)),
                ('execution_time', models.FloatField(help_text='Time taken to execute (seconds)')),
                ('memory_usage', models.IntegerField(blank=True, help_text='Memory used during execution (KB)', null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.ForeignKey(blank=True, help_text='Related code snippet if saved', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='code_editor.codesnippet')),
                ('user', models.ForeignKey(help_text='User who executed the code', on_delete=django.db.models.deletion.CASCADE, related_name='code_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='codesnippet',
            index=models.Index(fields=['user', 'language'], name='code_editor_user_id_d118b8_idx'),
        ),
        migrations.AddIndex(
            model_name='codesnippet',
            index=models.Index(fields=['is_public', 'created_at'], name='code_editor_is_publ_eae3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='executionhistory',
            index=models.Index(fields=['user', 'status'], name='code_editor_user_id_de6943_idx'),
        ),
        migrations.AddIndex(
            model_name='executionhistory',
            index=models.Index(fields=['executed_at'], name='code_editor_execute_5ed7ed_idx'),
        ),
    ]
