# Generated by Django 5.1.1 on 2024-11-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_editor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeTemplate',
        ),
        migrations.DeleteModel(
            name='ExecutionHistory',
        ),
    ]
