# Generated by Django 5.1.1 on 2024-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in-progress', 'In Progress'), ('done', 'Done'), ('backlog', 'Backlog'), ('canceled', 'Canceled')], default='todo', max_length=20),
        ),
    ]
