# Generated by Django 5.1.1 on 2024-10-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('no class', 'No Class')], max_length=10)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.enrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'attendance_date')},
            },
        ),
    ]
